# fly.toml app configuration file generated for reactivities-course-yk on 2023-10-23T23:15:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-course-yk"
primary_region = "sin"

[build]
  image = "yewkwong/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dkfotujxy"
  Cloudinary__ApiKey="363833538545542"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
